### ISSUE TITLE
is there a link or repo that has a datepicker leveraging this fiscal-fns

### ISSUE THREAD

**Issue by jsdev** [Ed-ITSolutions/fiscal-fns#1]
would be a great link to add to the Readme.md

**Comment by Arcath** [comment]
We use `fiscal-fns` in an api to ensure we only return data for this fiscal year so I don't have any examples to hand.

`fiscal-fns` uses and imitates `date-fns` so I'd look for an example using the function from that library and swap out the functions for the ones from `fiscal-fns`.
